# Generated by Django 5.2.10 on 2026-01-29 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class name", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Event Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="Brief description for listings", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Full event description with rich text"),
                ),
                (
                    "agenda",
                    models.TextField(blank=True, help_text="Event schedule and agenda"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("in-person", "In Person"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="in-person",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("timezone", models.CharField(default="Africa/Accra", max_length=50)),
                ("venue_name", models.CharField(max_length=300)),
                ("venue_address", models.TextField()),
                (
                    "venue_details",
                    models.TextField(
                        blank=True, help_text="Additional venue information"
                    ),
                ),
                ("venue_map_url", models.URLField(blank=True)),
                ("virtual_meeting_url", models.URLField(blank=True)),
                (
                    "virtual_meeting_password",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="events/featured/%Y/%m/"),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website_url", models.URLField(blank=True)),
                ("registration_required", models.BooleanField(default=True)),
                (
                    "registration_url",
                    models.URLField(blank=True, help_text="External registration link"),
                ),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "max_attendees",
                    models.PositiveIntegerField(default=0, help_text="0 for unlimited"),
                ),
                ("registered_count", models.PositiveIntegerField(default=0)),
                ("allow_waitlist", models.BooleanField(default=True)),
                ("waitlist_count", models.PositiveIntegerField(default=0)),
                ("registration_instructions", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "early_bird_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("early_bird_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("bookmarks_count", models.PositiveIntegerField(default=0)),
                ("cancellation_policy", models.TextField(blank=True)),
                ("covid_safety_measures", models.TextField(blank=True)),
                ("parking_info", models.TextField(blank=True)),
                ("accessibility_info", models.TextField(blank=True)),
                ("facebook_event_url", models.URLField(blank=True)),
                ("twitter_hashtag", models.CharField(blank=True, max_length=100)),
                ("livestream_url", models.URLField(blank=True)),
                (
                    "check_in_code",
                    models.CharField(
                        blank=True, help_text="QR code for check-in", max_length=20
                    ),
                ),
                ("certificate_template", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.eventcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("is_cover", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("early_bird", "Early Bird"),
                            ("vip", "VIP"),
                            ("student", "Student"),
                            ("group", "Group"),
                            ("complimentary", "Complimentary"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("ticket_number", models.CharField(max_length=50, unique=True)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("confirmed", "Confirmed"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("not_checked_in", "Not Checked In"),
                            ("checked_in", "Checked In"),
                            ("no_show", "No Show"),
                        ],
                        default="not_checked_in",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="Dietary, accessibility needs, etc."
                    ),
                ),
                ("accept_terms", models.BooleanField(default=False)),
                ("is_speaker", models.BooleanField(default=False)),
                ("is_vip", models.BooleanField(default=False)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("send_at", models.DateTimeField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["send_at"],
            },
        ),
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="events/speakers/")),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_username", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("logo", models.ImageField(upload_to="events/sponsors/")),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "sponsorship_level",
                    models.CharField(
                        choices=[
                            ("title", "Title Sponsor"),
                            ("platinum", "Platinum"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("partner", "Partner"),
                        ],
                        default="partner",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "sponsorship_level", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date", "status"], name="events_even_start_d_9e40f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_even_slug_30eb0f_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer"], name="events_even_organiz_266ef7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_featured", "is_trending"],
                name="events_even_is_feat_b1c4fd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["event", "status"], name="events_even_event_i_cdd3f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventregistration",
            index=models.Index(
                fields=["ticket_number"], name="events_even_ticket__605189_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "user")},
        ),
    ]
