# Generated by Django 5.2.10 on 2026-01-29 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Internal title", max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "newsletter_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Newsletter"),
                            ("special", "Special Announcement"),
                            ("digest", "Weekly/Monthly Digest"),
                            ("breaking", "Breaking News"),
                            ("promotional", "Promotional"),
                            ("event", "Event Invitation"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=200),
                ),
                (
                    "preheader",
                    models.CharField(
                        blank=True, help_text="Preview text", max_length=200
                    ),
                ),
                ("content_html", models.TextField(help_text="HTML content")),
                ("content_text", models.TextField(help_text="Plain text content")),
                ("template_used", models.CharField(blank=True, max_length=100)),
                (
                    "featured_news",
                    models.JSONField(
                        blank=True, default=list, help_text="List of news IDs"
                    ),
                ),
                (
                    "featured_events",
                    models.JSONField(
                        blank=True, default=list, help_text="List of event IDs"
                    ),
                ),
                (
                    "featured_opportunities",
                    models.JSONField(
                        blank=True, default=list, help_text="List of opportunity IDs"
                    ),
                ),
                (
                    "featured_announcements",
                    models.JSONField(
                        blank=True, default=list, help_text="List of announcement IDs"
                    ),
                ),
                ("send_to_all", models.BooleanField(default=False)),
                (
                    "target_segments",
                    models.JSONField(
                        blank=True, default=dict, help_text="Segment targeting criteria"
                    ),
                ),
                ("send_to_news", models.BooleanField(default=False)),
                ("send_to_events", models.BooleanField(default=False)),
                ("send_to_opportunities", models.BooleanField(default=False)),
                ("send_to_announcements", models.BooleanField(default=False)),
                ("send_to_diaspora", models.BooleanField(default=False)),
                (
                    "test_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of test email addresses",
                    ),
                ),
                ("use_personalization", models.BooleanField(default=True)),
                (
                    "from_name",
                    models.CharField(default="Ghana Notice Board", max_length=100),
                ),
                (
                    "from_email",
                    models.EmailField(
                        default="newsletter@ghanaticeboard.com", max_length=254
                    ),
                ),
                ("reply_to_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("recipients_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("opened_count", models.PositiveIntegerField(default=0)),
                ("clicked_count", models.PositiveIntegerField(default=0)),
                ("unsubscribed_count", models.PositiveIntegerField(default=0)),
                ("bounced_count", models.PositiveIntegerField(default=0)),
                ("complained_count", models.PositiveIntegerField(default=0)),
                ("is_ab_test", models.BooleanField(default=False)),
                ("ab_test_percentage", models.PositiveIntegerField(default=50)),
                ("variant_subject", models.CharField(blank=True, max_length=200)),
                ("variant_content_html", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "subscribe_news",
                    models.BooleanField(default=True, help_text="News updates"),
                ),
                (
                    "subscribe_events",
                    models.BooleanField(default=True, help_text="Event announcements"),
                ),
                (
                    "subscribe_opportunities",
                    models.BooleanField(
                        default=True, help_text="Job and opportunity alerts"
                    ),
                ),
                (
                    "subscribe_announcements",
                    models.BooleanField(
                        default=True, help_text="Official announcements"
                    ),
                ),
                (
                    "subscribe_diaspora",
                    models.BooleanField(default=False, help_text="Diaspora updates"),
                ),
                (
                    "subscribe_special",
                    models.BooleanField(
                        default=True, help_text="Special offers and promotions"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("monthly", "Monthly Roundup"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        default="en", help_text="Preferred language code", max_length=10
                    ),
                ),
                (
                    "preferred_categories",
                    models.JSONField(
                        blank=True, default=list, help_text="List of category IDs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_token",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "referrer",
                    models.CharField(
                        blank=True, help_text="How they subscribed", max_length=200
                    ),
                ),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("emails_opened", models.PositiveIntegerField(default=0)),
                ("links_clicked", models.PositiveIntegerField(default=0)),
                ("last_email_sent", models.DateTimeField(blank=True, null=True)),
                ("last_opened", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribe_reason", models.TextField(blank=True)),
                (
                    "unsubscribe_token",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "email_id",
                    models.CharField(
                        blank=True,
                        help_text="Email service provider ID",
                        max_length=200,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("first_click_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("clicked_links", models.JSONField(blank=True, default=list)),
                ("bounce_type", models.CharField(blank=True, max_length=50)),
                ("bounce_reason", models.TextField(blank=True)),
                ("is_variant", models.BooleanField(default=False)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="newsletters.newsletter",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="newsletters.newslettersubscriber",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Newsletter"),
                            ("digest", "Digest"),
                            ("event", "Event Announcement"),
                            ("special", "Special Announcement"),
                            ("promotional", "Promotional"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "html_template",
                    models.TextField(help_text="HTML template with placeholders"),
                ),
                (
                    "text_template",
                    models.TextField(help_text="Plain text template with placeholders"),
                ),
                (
                    "css_styles",
                    models.TextField(blank=True, help_text="Custom CSS styles"),
                ),
                ("has_header", models.BooleanField(default=True)),
                ("has_footer", models.BooleanField(default=True)),
                ("has_social_links", models.BooleanField(default=True)),
                (
                    "sections",
                    models.JSONField(
                        default=list, help_text="Available content sections"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(
                fields=["status", "scheduled_for"], name="newsletters_status_47c5bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(fields=["slug"], name="newsletters_slug_ee5697_idx"),
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(
                fields=["-created_at"], name="newsletters_created_1a7d70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(
                fields=["status", "frequency"], name="newsletters_status_8def46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(fields=["email"], name="newsletters_email_82b4b7_idx"),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(
                fields=["confirmation_token"], name="newsletters_confirm_78f16b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletteremail",
            index=models.Index(
                fields=["newsletter", "status"], name="newsletters_newslet_d35335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletteremail",
            index=models.Index(
                fields=["subscriber"], name="newsletters_subscri_7aaada_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="newsletteremail",
            unique_together={("newsletter", "subscriber")},
        ),
    ]
