# Generated by Django 5.2.10 on 2026-01-29 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("feedback", "Feedback"),
                            ("complaint", "Complaint"),
                            ("suggestion", "Suggestion"),
                            ("partnership", "Partnership Proposal"),
                            ("advertising", "Advertising Inquiry"),
                            ("press", "Press Inquiry"),
                            ("technical", "Technical Issue"),
                            ("content", "Content Related"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "referrer",
                    models.CharField(
                        blank=True, help_text="How they found us", max_length=200
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to="contact/attachments/%Y/%m/"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_responded", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("is_spam", models.BooleanField(default=False)),
                ("response_notes", models.TextField(blank=True)),
                ("response_sent_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inquiry_type", "is_resolved"],
                        name="submissions_inquiry_633327_idx",
                    ),
                    models.Index(
                        fields=["priority", "is_read"],
                        name="submissions_priorit_bbd294_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="submissions_created_e0428d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("news", "News Tip"),
                            ("event", "Event Submission"),
                            ("announcement", "Announcement"),
                            ("opportunity", "Opportunity"),
                            ("diaspora", "Diaspora Story"),
                            ("report", "Investigative Report"),
                            ("opinion", "Opinion Piece"),
                            ("press-release", "Press Release"),
                            ("community", "Community News"),
                            ("photo", "Photo Story"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "summary",
                    models.CharField(
                        default="", help_text="Brief summary", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Full content")),
                ("submitter_name", models.CharField(max_length=200)),
                ("submitter_email", models.EmailField(max_length=254)),
                ("submitter_phone", models.CharField(blank=True, max_length=20)),
                (
                    "submitter_organization",
                    models.CharField(blank=True, max_length=200),
                ),
                ("submitter_location", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location relevant to submission",
                        max_length=200,
                    ),
                ),
                ("event_date", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Comma-separated tags"),
                ),
                (
                    "sources",
                    models.TextField(blank=True, help_text="Sources or references"),
                ),
                ("additional_info", models.JSONField(blank=True, default=dict)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, upload_to="submissions/images/%Y/%m/"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, upload_to="submissions/documents/%Y/%m/"
                    ),
                ),
                ("document_title", models.CharField(blank=True, max_length=200)),
                (
                    "additional_images",
                    models.JSONField(
                        blank=True, default=list, help_text="URLs of additional images"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False, help_text="Hide submitter identity"
                    ),
                ),
                (
                    "is_exclusive",
                    models.BooleanField(default=False, help_text="Exclusive content"),
                ),
                ("requires_fact_check", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for reviewers"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("fact_check_notes", models.TextField(blank=True)),
                (
                    "published_as_type",
                    models.CharField(
                        blank=True,
                        help_text="Content type when published",
                        max_length=20,
                    ),
                ),
                (
                    "published_as_id",
                    models.UUIDField(
                        blank=True, help_text="ID of published content", null=True
                    ),
                ),
                ("published_url", models.URLField(blank=True)),
                ("compensation_offered", models.BooleanField(default=False)),
                (
                    "compensation_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_status", models.CharField(blank=True, max_length=20)),
                ("payment_notes", models.TextField(blank=True)),
                ("copyright_agreement", models.BooleanField(default=False)),
                ("verification_consent", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission_type", "status"],
                        name="submissions_submiss_953b8b_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="submissions_priorit_dac131_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="submissions_created_b59eeb_idx"
                    ),
                    models.Index(fields=["slug"], name="submissions_slug_9d0ca2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedbackSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("feature", "Feature Request"),
                            ("bug", "Bug Report"),
                            ("improvement", "Improvement Suggestion"),
                            ("compliment", "Compliment"),
                            ("complaint", "Complaint"),
                            ("content", "Content Feedback"),
                            ("ui", "UI/UX Feedback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "page_url",
                    models.URLField(
                        blank=True, help_text="Page where feedback was given"
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("content_id", models.UUIDField(blank=True, null=True)),
                (
                    "overall_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "ease_of_use_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "content_quality_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, upload_to="feedback/screenshots/%Y/%m/"
                    ),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                ("is_implemented", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Show in public feedback section"
                    ),
                ),
                ("admin_response", models.TextField(blank=True)),
                ("implementation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feedback_type", "is_reviewed"],
                        name="submissions_feedbac_8e5193_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="submissions_created_33a072_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("misinformation", "Misinformation"),
                            ("copyright", "Copyright Violation"),
                            ("harassment", "Harassment"),
                            ("hate_speech", "Hate Speech"),
                            ("violence", "Violence"),
                            ("adult", "Adult Content"),
                            ("scam", "Scam/Fraud"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("reported_content_type", models.CharField(max_length=50)),
                ("reported_content_id", models.UUIDField()),
                ("reported_content_url", models.URLField(blank=True)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, upload_to="reports/screenshots/%Y/%m/"
                    ),
                ),
                ("additional_info", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("valid", "Valid Report"),
                            ("invalid", "Invalid Report"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "status"],
                        name="submissions_report__de4cb0_idx",
                    ),
                    models.Index(
                        fields=["reported_content_type", "reported_content_id"],
                        name="submissions_reporte_99c3bb_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="submissions_created_e043bd_idx"
                    ),
                ],
            },
        ),
    ]
