# Generated by Django 5.2.10 on 2026-01-12 18:33

import authentication.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tags', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('twitter_username', models.CharField(blank=True, max_length=50, verbose_name='Twitter username')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_username', models.CharField(blank=True, max_length=50, verbose_name='GitHub username')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=authentication.models.user_avatar_path, verbose_name='avatar')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=authentication.models.user_cover_path, verbose_name='cover image')),
                ('is_public', models.BooleanField(default=True, verbose_name='public profile')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='push notifications')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verification_badge', models.CharField(blank=True, max_length=50, verbose_name='verification badge')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='posts count')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='followers count')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='following count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='last seen')),
                ('user_type', models.CharField(choices=[('regular', 'Regular User'), ('journalist', 'Journalist'), ('organization', 'Organization'), ('government', 'Government Official'), ('verified', 'Verified Account')], default='regular', max_length=20, verbose_name='user type')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='occupation')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='company')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='skills')),
                ('show_email', models.BooleanField(default=False, verbose_name='show email')),
                ('show_location', models.BooleanField(default=True, verbose_name='show location')),
                ('allow_messages', models.BooleanField(default=True, verbose_name='allow messages')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20, verbose_name='theme')),
                ('language', models.CharField(choices=[('en', 'English'), ('tw', 'Twi'), ('ga', 'Ga'), ('ee', 'Ewe')], default='en', max_length=10, verbose_name='language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_users', to='tags.tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_d74434_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='authenticat_usernam_61ef80_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='authenticat_created_b28532_idx'),
        ),
    ]
