# Generated by Django 5.2.10 on 2026-01-29 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="Brief summary for listings", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="Full announcement content")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("government", "Government Notice"),
                            ("public_service", "Public Service"),
                            ("emergency", "Emergency Alert"),
                            ("health", "Health Advisory"),
                            ("education", "Education Notice"),
                            ("community", "Community Announcement"),
                            ("legal", "Legal Notice"),
                            ("tender", "Tender/Procurement"),
                            ("policy", "Policy Update"),
                            ("infrastructure", "Infrastructure Update"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("general", "General Public"),
                            ("students", "Students"),
                            ("businesses", "Businesses"),
                            ("farmers", "Farmers"),
                            ("health_workers", "Health Workers"),
                            ("teachers", "Teachers"),
                            ("diaspora", "Diaspora"),
                            ("specific_region", "Specific Region"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("source_organization", models.CharField(max_length=200)),
                (
                    "organization_logo",
                    models.ImageField(blank=True, upload_to="announcements/logos/"),
                ),
                ("organization_verified", models.BooleanField(default=False)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Official reference number",
                        max_length=100,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_address", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                (
                    "is_national",
                    models.BooleanField(
                        default=True, help_text="Applies to entire Ghana"
                    ),
                ),
                (
                    "regions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of regions"
                    ),
                ),
                (
                    "districts",
                    models.JSONField(
                        blank=True, default=list, help_text="List of districts"
                    ),
                ),
                ("location_details", models.TextField(blank=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, upload_to="announcements/featured/%Y/%m/"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, upload_to="announcements/documents/%Y/%m/"
                    ),
                ),
                ("document_title", models.CharField(blank=True, max_length=200)),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="YouTube or other video URL"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False,
                        help_text="Emergency alert requiring immediate attention",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="Pin to top of lists"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule for future publication",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When announcement expires", null=True
                    ),
                ),
                ("requires_acknowledgment", models.BooleanField(default=False)),
                ("legal_disclaimer", models.TextField(blank=True)),
                (
                    "related_law",
                    models.CharField(
                        blank=True,
                        help_text="Related law or regulation",
                        max_length=300,
                    ),
                ),
                ("action_required", models.BooleanField(default=False)),
                ("action_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "action_url",
                    models.URLField(blank=True, help_text="URL for required action"),
                ),
                ("action_instructions", models.TextField(blank=True)),
                ("is_ai_translated", models.BooleanField(default=False)),
                (
                    "ai_translations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Translations in local languages",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="AI-generated summary"),
                ),
                (
                    "ai_keywords",
                    models.TextField(blank=True, help_text="AI-extracted keywords"),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("acknowledgments_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("published", "Published"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approval_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_promoted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    "-is_emergency",
                    "-is_pinned",
                    "-priority",
                    "-published_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnnouncementImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="announcements/gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("tw", "Twi"),
                            ("ee", "Ewe"),
                            ("ga", "Ga"),
                            ("dag", "Dagbani"),
                            ("ha", "Hausa"),
                            ("nz", "Nzema"),
                        ],
                        max_length=3,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("is_machine_translated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
