# Generated by Django 5.2.10 on 2026-01-12 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('tags', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='tags.category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementacknowledgment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementacknowledgment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acknowledgments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementalert',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementalert',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementimage',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementtranslation',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='announcementtranslation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['announcement_type', 'status'], name='announcemen_announc_eccb99_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_emergency', 'is_pinned'], name='announcemen_is_emer_e7186d_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['slug'], name='announcemen_slug_f2402f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expires_at'], name='announcemen_expires_854584_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience'], name='announcemen_target__f9678f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementacknowledgment',
            index=models.Index(fields=['announcement', 'user'], name='announcemen_announc_d93e23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementacknowledgment',
            unique_together={('announcement', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='announcementtranslation',
            unique_together={('announcement', 'language')},
        ),
    ]
