# Generated by Django 5.2.10 on 2026-01-29 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, max_length=350, unique=True)),
                (
                    "summary",
                    models.CharField(
                        help_text="Brief description for listings", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full description with requirements and benefits"
                    ),
                ),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("job", "Job"),
                            ("scholarship", "Scholarship"),
                            ("grant", "Grant"),
                            ("internship", "Internship"),
                            ("fellowship", "Fellowship"),
                            ("volunteer", "Volunteer"),
                            ("business", "Business Opportunity"),
                            ("funding", "Funding"),
                            ("mentorship", "Mentorship"),
                            ("training", "Training/Workshop"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                (
                    "organization_logo",
                    models.ImageField(blank=True, upload_to="opportunities/logos/"),
                ),
                ("organization_website", models.URLField(blank=True)),
                ("organization_description", models.TextField(blank=True)),
                ("organization_verified", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Ghana", max_length=100)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "is_diaspora",
                    models.BooleanField(
                        default=False, help_text="Opportunity for diaspora"
                    ),
                ),
                ("relocation_assistance", models.BooleanField(default=False)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                            ("temporary", "Temporary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("executive", "Executive"),
                            ("internship", "Internship"),
                            ("no-experience", "No Experience Required"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="GHS", max_length=3)),
                ("show_salary", models.BooleanField(default=True)),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="List of benefits"),
                ),
                ("education_requirement", models.TextField(blank=True)),
                ("experience_requirement", models.TextField(blank=True)),
                ("skills_required", models.TextField(blank=True)),
                ("languages_required", models.TextField(blank=True)),
                ("certifications_required", models.TextField(blank=True)),
                (
                    "funding_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "funding_currency",
                    models.CharField(blank=True, default="GHS", max_length=3),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="Duration of opportunity", max_length=100
                    ),
                ),
                ("eligibility_criteria", models.TextField(blank=True)),
                ("selection_process", models.TextField(blank=True)),
                ("number_of_slots", models.PositiveIntegerField(default=1)),
                (
                    "application_method",
                    models.CharField(default="external", max_length=50),
                ),
                ("application_url", models.URLField(blank=True)),
                ("application_email", models.EmailField(blank=True, max_length=254)),
                ("application_instructions", models.TextField(blank=True)),
                (
                    "required_documents",
                    models.TextField(
                        blank=True, help_text="List of required documents"
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, upload_to="opportunities/featured/%Y/%m/"
                    ),
                ),
                ("is_ai_enhanced", models.BooleanField(default=False)),
                (
                    "ai_match_keywords",
                    models.TextField(
                        blank=True, help_text="AI-generated keywords for matching"
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="AI-generated summary"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("published", "Published"),
                            ("expired", "Expired"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_urgent", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("shares_count", models.PositiveIntegerField(default=0)),
                ("bookmarks_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="tags.category",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_urgent", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=200)),
                (
                    "cv_file",
                    models.FileField(blank=True, upload_to="applications/cvs/%Y/%m/"),
                ),
                ("cover_letter", models.TextField()),
                ("portfolio_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("current_position", models.CharField(blank=True, max_length=200)),
                ("current_company", models.CharField(blank=True, max_length=200)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("availability", models.CharField(blank=True, max_length=100)),
                ("references", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("interview_date", models.DateTimeField(blank=True, null=True)),
                ("interview_location", models.CharField(blank=True, max_length=300)),
                ("interview_notes", models.TextField(blank=True)),
                ("ai_match_score", models.FloatField(blank=True, null=True)),
                ("ai_match_reasons", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "opportunity_types",
                    models.JSONField(
                        default=list, help_text="List of opportunity types"
                    ),
                ),
                (
                    "keywords",
                    models.TextField(blank=True, help_text="Comma-separated keywords"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_remote_only", models.BooleanField(default=False)),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="opportunities/gallery/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this opportunity"
                    ),
                ),
                ("reminder_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["opportunity_type", "status"],
                name="opportuniti_opportu_f05940_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["deadline"], name="opportuniti_deadlin_294f61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["slug"], name="opportuniti_slug_2181ad_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["is_featured", "is_trending"],
                name="opportuniti_is_feat_222fb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["opportunity", "status"], name="opportuniti_opportu_3d9fba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applicant"], name="opportuniti_applica_bec37d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("opportunity", "applicant")},
        ),
        migrations.AlterUniqueTogether(
            name="savedopportunity",
            unique_together={("user", "opportunity")},
        ),
    ]
